### ISSUE TITLE
E-Mail Versand funktioniert nicht

### ISSUE THREAD

**Issue by micdis** [toafez/BasicBackup#3]
Vielen Dank für dieses geniale Projekt! :- )

Ein kleines Problem hab ich jedoch, dem ich nicht Herr werde:

In den Systemeinstellungen unter Benachrichtigungen ist eine gmail-Adresse hinterlegt und ein Empfänger mit anderer TLD. Für die nächtlichen Backups über HyperBAckup bekomme ich dort auch unkompliziert mails. BasicBackup schreibt jedoch immer ins log:

` Das Versenden des Datensicherungsprotokolls per E-Mail ist fehlgeschlagen!`

Der Versender und Empfänger sind jedoch identisch zu den Synology-Einstellungen.
Eine Idee, woran das liegen kann?

Dank und Gruß,
Michael

**Comment by toafez** [comment]
Hi!

Zuerst mal ein Schuß ins Blaue, da ich wohl erst morgen dazu komme, mir das näher anzuschauen. Beim Erstellen bzw. Editieren eines Basic Backup Auftrages kannst du zu den Eingabefeldern Absender- und Empfängeradresse einen Hilfetext aufrufen. Hast du diesen (siehe nachfolgenden Text) beachtet?

> Die E-Mail Adresse des Absenders muss gleich der im DSM unter Hauptmenü > Systemsteuerung > Benachrichtigung > E-Mail angegebenen Absenderadresse sein. Ansonsten wird keine E-Mail bzw. kein Sicherungsprotokoll zugestellt.

Ich schau mir das morgen aber selber noch mal an.

**Comment by micdis** [comment]
Hi!

vielen Dank für die Rückmeldung. Ich hab die Adressen nochmals kontrolliert und beide (sowohl Absender als auch Empfänger) sind identisch zu den im DSM eingetragenen!

Gibt es die Möglichkeit des ausführlicheren Loggings? Kann es mit dem Anbieter zu tun haben!? Bei Gelegenheit kann ich mal einen individuellen SMTP testen...

Dank und Gruß,
Michael

**Comment by toafez** [comment]
Hi!

Ich habe ein kleines Funktionsupdate für Basic Backup ausgegeben, welches auch einen "Verbose" für das SMTP Protokoll enthält. Hierzu ein Auszug aus den Release-Notes:

> SMTP-Debug Mode hinzugefügt. Wird dem Befehl zum ausführen eines Auftrages der Optionsschalter -v angehangen, werden neben den breits vorhandenen, erweiterten Ausgaben, nun auch ausführlichere Informationen zum Verbindungsaufbau sowie dem Versand einer E-Mail per SMTP ausgegeben.

Das Ergebnis der Ausgabe findest du im Datensicherungsprotokoll deines entsrechenden Auftrages. Du kannst den Befehl zum ausführen eines Auftrages auch direkt auf der Konsole ausführen (mit angehängtem -v), dann siehst du ebenfalls die Ausgabe des SMTP Debug Mode.

Du kannst dir die aktuelle Version 0.6-500 [hier](https://github.com/toafez/BasicBackup/releases/download/0.6-500/BasicBackup_0.6-500.spk) herunterladen 

Schau mal, ob dich das weiter bringt.

toafez

**Comment by micdis** [comment]
wow, vielen Dank.

Es war ein Authentifizierungs-Problem. Der Wechsel zu "benutzerdefinierter SMTP" und Erstellung eines App-Spezifischen Passworts auf googele-seite hat das Problem gelöst.
